function Run_UC(case, current_path_folder)
    base_MVA    = 100.0         # Base Power [MVA]

    #-----------------------------------------
    Clean_Terminal() # Clean the terminal
    #-----------------------------------------

    #-----------------------------------------
    # Generate a folder to export the results
    #-----------------------------------------
    name_path_results   = "Results"                                        # Name of the folder to save the results (it must be created in advance)
    path_folder_results = joinpath(current_path_folder, name_path_results) # Results directory
    cd(current_path_folder)                                                # Load the current folder

    #------------------------------------------
    # Call the function to read the input data
    #------------------------------------------
    input_data_path_folder = joinpath(current_path_folder, "Input_Data", case) # Folder name where the input data is located

    # Get the structs with data related to buses, generators and circuits
    DBUS, DGEN, DCIR, bus_mapping, reverse_bus_mapping = Read_Input_Data(input_data_path_folder) 

    # ---------------------------------------------------
    nBUS = length(DBUS.bus)      # Number of buses in the system
    nGEN = length(DGEN.id)       # Number of generators in the system
    nCIR = length(DCIR.from_bus) # Number of circuits in the system
    cd(current_path_folder)      # Load the current folder

    cost = DGEN.g_cost  # €/MWh
    Pₘᵢₙ = DGEN.pg_min  # Minimum power of each generator, MW
    Pₘₐₓ = DGEN.pg_max  # Maximum power of each generator, MW
    Demand = sum(DBUS.p_d) # Sum of all demands

    # ########################################################################################
    #                                 STARTS OPTIMIZATION PROCESS 

    #-----------------------------------
    # Optimization model -> Setup
    #-----------------------------------
    model = JuMP.Model(HiGHS.Optimizer)
    JuMP.set_optimizer_attribute(model, "mip_rel_gap", 1e-8)    # Set optimality tolerance

    # Define Decision Variables for power generated by each unit:
    @variable(model, P_g[n in 1:nGEN]) # MW

    # Define Decision Variables for the one/off state of each unit:
    @variable(model, y_g[n in 1:nGEN], Bin) # binary variable indicating if generator g is ON (1) or OFF (0)

    # Define the constraints:
    @constraint(model, y_g .* Pₘᵢₙ .<= P_g) # MW
    @constraint(model, P_g .<= y_g .* Pₘₐₓ) # MW
    # @constraint(model, [g in 1:nGEN], P_g[g] >= Pₘᵢₙ[g] * y_g[g])
    # @constraint(model, [g in 1:nGEN], P_g[g] <= Pₘₐₓ[g] * y_g[g])
    @constraint(model, power_balance, sum(P_g) == Demand)  # Total power output equals demand

    # Define the objective function 
    Total_cost = cost' * P_g

    @objective(model, Min, Total_cost)

    print(model)
    println()

    ##############

    ## Solve the optimization problem
    optimize!(model)

    ##############

    ## Get the solution
    println()
    println("##########################################")
    println()
    println("SOLUCIÓN:")
    println()

    println("COSTE TOTAL: ", value(Total_cost), " €")
    println()

    println("COMMITMENT GENERADOR:")
    for i in 1:nGEN
        commitment = value(y_g[i])
        status = ""
        if isapprox(commitment, 0; atol = 1e-1)
            status = "OFF"
        elseif isapprox(commitment, 1; atol = 1e-1)
            status = "ON"
        end
        println("  - Generador $i: ", status, "")
    end
    println()

    println("POTENCIA GENERADA:")
    for i in 1:nGEN
        println("  - Generador $i: ", value(P_g[i]), " MW")
    end
    println() 
    
    cd(path_folder_results)
    # Save the solution in a txt file
    open("7_solucion_UC.txt", "w") do file

        println(file)
        println(file, "##########################################")
        println(file)
        println(file, "SOLUCIÓN:")
        println(file)

        println(file, "COSTE TOTAL: ", value(Total_cost), " €")
        println(file)

        println(file, "COMMITMENT GENERADOR:")
        for i in 1:nGEN
            commitment = value(y_g[i])
            status = ""
            if isapprox(commitment, 0; atol = 1e-1)
                status = "OFF"
            elseif isapprox(commitment, 1; atol = 1e-1)
                status = "ON"
            end
            println(file, "  - Generador $i: ", status, "")
        end
        println(file)

        println(file, "POTENCIA GENERADA:")
        for i in 1:nGEN
            println(file, "  - Generador $i: ", value(P_g[i]), " MW")
        end
        println(file)

    end
    cd(current_path_folder)

    #                               ENDS OPTIMIZATION PROCESS 
    # ########################################################################################
    println("--------------------------------------------------------------------------------------------------------------------------------------")
end